### ISSUE TITLE
Modify API endpoint for obtaining masks and regional maps

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-matlab#22]
When queried for a regional map in aprticular space, siibra-API should return the URL to a volume as well as (in case of labelled maps) the label index identifying the region.

**Comment by xgui3783** [comment]
should be resolved by https://github.com/FZJ-INM1-BDA/siibra-api/commit/4b90017bbd341e4034d7145b4ede296937214bc4

e.g. https://siibra-api-stable.apps.hbp.eu/v1_0/docs#/parcellations/get_regional_map_info_atlases__atlas_id__parcellations__parcellation_id__regions__region_id__regional_map_info_get
